apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
data:
  SERVICE_BUS_FQDN: "stormbreaker-servicebusgbb.servicebus.windows.net"
  SERVICE_BUS_QUEUE_DISPATCH: "stormbreaker-dispatch"
  SERVICE_BUS_QUEUE_RUNNING: "stormbreaker-running"
  SERVICE_BUS_QUEUE_DELETE: "stormbreaker-delete"
  REACT_APP_STORMBREAKER_API_HOST: "localhost"
  REACT_APP_STORMBREAKER_API_PORT: "8001"
